ol.proj.proj4.register(proj4);
//ol.proj.get("EPSG:32632").setExtent([536552.312500, 5067967.500000, 549404.187500, 5091338.500000]);
var wms_layers = [];


        var lyr_GoogleSatellite_0 = new ol.layer.Tile({
            'title': 'Google Satellite',
            'opacity': 0.855000,
            
            
            source: new ol.source.XYZ({
            attributions: '&nbsp;&middot; <a href="https://www.google.at/permissions/geoguidelines/attr-guide.html">Map data ©2015 Google</a>',
                url: 'https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}'
            })
        });

        var lyr_GoogleLabels_1 = new ol.layer.Tile({
            'title': 'Google Labels',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: '&nbsp;&middot; <a href="https://www.google.at/permissions/geoguidelines/attr-guide.html">Map data ©2015 Google</a>',
                url: 'https://mt1.google.com/vt/lyrs=h&x={x}&y={y}&z={z}'
            })
        });
var format_Sentieri_2 = new ol.format.GeoJSON();
var features_Sentieri_2 = format_Sentieri_2.readFeatures(json_Sentieri_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32632'});
var jsonSource_Sentieri_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Sentieri_2.addFeatures(features_Sentieri_2);
var lyr_Sentieri_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Sentieri_2, 
                style: style_Sentieri_2,
                popuplayertitle: 'Sentieri',
                interactive: false,
                title: '<img src="styles/legend/Sentieri_2.png" /> Sentieri'
            });
var format_Capriateligneedirilievoartistico_3 = new ol.format.GeoJSON();
var features_Capriateligneedirilievoartistico_3 = format_Capriateligneedirilievoartistico_3.readFeatures(json_Capriateligneedirilievoartistico_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32632'});
var jsonSource_Capriateligneedirilievoartistico_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Capriateligneedirilievoartistico_3.addFeatures(features_Capriateligneedirilievoartistico_3);
var lyr_Capriateligneedirilievoartistico_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Capriateligneedirilievoartistico_3, 
                style: style_Capriateligneedirilievoartistico_3,
                popuplayertitle: 'Capriate lignee di rilievo artistico',
                interactive: false,
                title: '<img src="styles/legend/Capriateligneedirilievoartistico_3.png" /> Capriate lignee di rilievo artistico'
            });
var format_Elementiartisticidipregiocornicimodanateaffreschifregi_4 = new ol.format.GeoJSON();
var features_Elementiartisticidipregiocornicimodanateaffreschifregi_4 = format_Elementiartisticidipregiocornicimodanateaffreschifregi_4.readFeatures(json_Elementiartisticidipregiocornicimodanateaffreschifregi_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32632'});
var jsonSource_Elementiartisticidipregiocornicimodanateaffreschifregi_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Elementiartisticidipregiocornicimodanateaffreschifregi_4.addFeatures(features_Elementiartisticidipregiocornicimodanateaffreschifregi_4);
var lyr_Elementiartisticidipregiocornicimodanateaffreschifregi_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Elementiartisticidipregiocornicimodanateaffreschifregi_4, 
                style: style_Elementiartisticidipregiocornicimodanateaffreschifregi_4,
                popuplayertitle: 'Elementi artistici di pregio (cornici modanate, affreschi, fregi)',
                interactive: false,
                title: '<img src="styles/legend/Elementiartisticidipregiocornicimodanateaffreschifregi_4.png" /> Elementi artistici di pregio (cornici modanate, affreschi, fregi)'
            });
var format_Aperturetrilitiche_5 = new ol.format.GeoJSON();
var features_Aperturetrilitiche_5 = format_Aperturetrilitiche_5.readFeatures(json_Aperturetrilitiche_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32632'});
var jsonSource_Aperturetrilitiche_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Aperturetrilitiche_5.addFeatures(features_Aperturetrilitiche_5);
var lyr_Aperturetrilitiche_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Aperturetrilitiche_5, 
                style: style_Aperturetrilitiche_5,
                popuplayertitle: 'Aperture trilitiche',
                interactive: false,
                title: '<img src="styles/legend/Aperturetrilitiche_5.png" /> Aperture trilitiche'
            });
var format_AperturetradizionaliaTconserramentoinlegno_6 = new ol.format.GeoJSON();
var features_AperturetradizionaliaTconserramentoinlegno_6 = format_AperturetradizionaliaTconserramentoinlegno_6.readFeatures(json_AperturetradizionaliaTconserramentoinlegno_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32632'});
var jsonSource_AperturetradizionaliaTconserramentoinlegno_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_AperturetradizionaliaTconserramentoinlegno_6.addFeatures(features_AperturetradizionaliaTconserramentoinlegno_6);
var lyr_AperturetradizionaliaTconserramentoinlegno_6 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_AperturetradizionaliaTconserramentoinlegno_6, 
                style: style_AperturetradizionaliaTconserramentoinlegno_6,
                popuplayertitle: 'Aperture tradizionali a T con serramento in legno',
                interactive: false,
                title: '<img src="styles/legend/AperturetradizionaliaTconserramentoinlegno_6.png" /> Aperture tradizionali a T con serramento in legno'
            });
var format_Tettoincoppidilaterizio_7 = new ol.format.GeoJSON();
var features_Tettoincoppidilaterizio_7 = format_Tettoincoppidilaterizio_7.readFeatures(json_Tettoincoppidilaterizio_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32632'});
var jsonSource_Tettoincoppidilaterizio_7 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Tettoincoppidilaterizio_7.addFeatures(features_Tettoincoppidilaterizio_7);
var lyr_Tettoincoppidilaterizio_7 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Tettoincoppidilaterizio_7, 
                style: style_Tettoincoppidilaterizio_7,
                popuplayertitle: 'Tetto in coppi di laterizio',
                interactive: false,
                title: '<img src="styles/legend/Tettoincoppidilaterizio_7.png" /> Tetto in coppi di laterizio'
            });
var format_Tettiinardesia_8 = new ol.format.GeoJSON();
var features_Tettiinardesia_8 = format_Tettiinardesia_8.readFeatures(json_Tettiinardesia_8, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32632'});
var jsonSource_Tettiinardesia_8 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Tettiinardesia_8.addFeatures(features_Tettiinardesia_8);
var lyr_Tettiinardesia_8 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Tettiinardesia_8, 
                style: style_Tettiinardesia_8,
                popuplayertitle: 'Tetti in ardesia',
                interactive: false,
                title: '<img src="styles/legend/Tettiinardesia_8.png" /> Tetti in ardesia'
            });
var format_Tettiinpiode_9 = new ol.format.GeoJSON();
var features_Tettiinpiode_9 = format_Tettiinpiode_9.readFeatures(json_Tettiinpiode_9, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32632'});
var jsonSource_Tettiinpiode_9 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Tettiinpiode_9.addFeatures(features_Tettiinpiode_9);
var lyr_Tettiinpiode_9 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Tettiinpiode_9, 
                style: style_Tettiinpiode_9,
                popuplayertitle: 'Tetti in piode',
                interactive: false,
                title: '<img src="styles/legend/Tettiinpiode_9.png" /> Tetti in piode'
            });
var format_Edificischedati_10 = new ol.format.GeoJSON();
var features_Edificischedati_10 = format_Edificischedati_10.readFeatures(json_Edificischedati_10, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32632'});
var jsonSource_Edificischedati_10 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Edificischedati_10.addFeatures(features_Edificischedati_10);
var lyr_Edificischedati_10 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Edificischedati_10, 
                style: style_Edificischedati_10,
                popuplayertitle: 'Edifici schedati',
                interactive: true,
                title: '<img src="styles/legend/Edificischedati_10.png" /> Edifici schedati'
            });
var format_Confinecomunale_11 = new ol.format.GeoJSON();
var features_Confinecomunale_11 = format_Confinecomunale_11.readFeatures(json_Confinecomunale_11, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:32632'});
var jsonSource_Confinecomunale_11 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Confinecomunale_11.addFeatures(features_Confinecomunale_11);
var lyr_Confinecomunale_11 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Confinecomunale_11, 
                style: style_Confinecomunale_11,
                popuplayertitle: 'Confine comunale',
                interactive: false,
                title: '<img src="styles/legend/Confinecomunale_11.png" /> Confine comunale'
            });
var group_Atlantedeicaratteriarchitettoniciidentitari = new ol.layer.Group({
                                layers: [lyr_Capriateligneedirilievoartistico_3,lyr_Elementiartisticidipregiocornicimodanateaffreschifregi_4,lyr_Aperturetrilitiche_5,lyr_AperturetradizionaliaTconserramentoinlegno_6,lyr_Tettoincoppidilaterizio_7,lyr_Tettiinardesia_8,lyr_Tettiinpiode_9,],
                                fold: 'open',
                                title: 'Atlante dei caratteri architettonici identitari'});
var group_EDIFICIDBGT = new ol.layer.Group({
                                layers: [],
                                fold: 'close',
                                title: 'EDIFICI DBGT'});
var group_percorsidavigente = new ol.layer.Group({
                                layers: [],
                                fold: 'close',
                                title: 'percorsi da vigente'});
var group_davigente = new ol.layer.Group({
                                layers: [],
                                fold: 'close',
                                title: 'da vigente'});
var group_base_dbt_per_pianificazione = new ol.layer.Group({
                                layers: [],
                                fold: 'close',
                                title: 'base_dbt_per_pianificazione'});

lyr_GoogleSatellite_0.setVisible(true);lyr_GoogleLabels_1.setVisible(false);lyr_Sentieri_2.setVisible(true);lyr_Capriateligneedirilievoartistico_3.setVisible(false);lyr_Elementiartisticidipregiocornicimodanateaffreschifregi_4.setVisible(false);lyr_Aperturetrilitiche_5.setVisible(false);lyr_AperturetradizionaliaTconserramentoinlegno_6.setVisible(false);lyr_Tettoincoppidilaterizio_7.setVisible(false);lyr_Tettiinardesia_8.setVisible(false);lyr_Tettiinpiode_9.setVisible(false);lyr_Edificischedati_10.setVisible(true);lyr_Confinecomunale_11.setVisible(true);
var layersList = [lyr_GoogleSatellite_0,lyr_GoogleLabels_1,lyr_Sentieri_2,group_Atlantedeicaratteriarchitettoniciidentitari,lyr_Edificischedati_10,lyr_Confinecomunale_11];
lyr_Sentieri_2.set('fieldAliases', {'fid': 'fid', 'tipo': 'tipo', 'Numero CAI sentiero': 'Numero CAI sentiero', });
lyr_Capriateligneedirilievoartistico_3.set('fieldAliases', {'fid': 'fid', 'scheda': 'scheda', 'Stato_2025': 'Stato_2025', 'pdf_link': 'pdf_link', 'A_Solaio_1': 'A_Solaio_1', 'A_Solaio_2': 'A_Solaio_2', 'B_Copert_tipo_1': 'B_Copert_tipo_1', 'B_Copert_tipo_2': 'B_Copert_tipo_2', 'B_Copert_tipo_3': 'B_Copert_tipo_3', 'B_Copert_tipo_4': 'B_Copert_tipo_4', 'C_Copert_str_1': 'C_Copert_str_1', 'C_Copert_str_2': 'C_Copert_str_2', 'C_Copert_str_3': 'C_Copert_str_3', 'D_Gronda_1': 'D_Gronda_1', 'D_Gronda_2': 'D_Gronda_2', 'E_Pluv_can_1': 'E_Pluv_can_1', 'E_Pluv_can_2': 'E_Pluv_can_2', 'F_Muri_1': 'F_Muri_1', 'F_Muri_2': 'F_Muri_2', 'F_Muri_3': 'F_Muri_3', 'G_Finestre_1': 'G_Finestre_1', 'G_Finestre_2': 'G_Finestre_2', 'H_Oscuranti_1': 'H_Oscuranti_1', 'H_Oscuranti_2': 'H_Oscuranti_2', 'H_Oscuranti_3': 'H_Oscuranti_3', 'I_Porte_1': 'I_Porte_1', 'I_Porte_2': 'I_Porte_2', 'I_Porte_3': 'I_Porte_3', 'J_Cornici_fin_1': 'J_Cornici_fin_1', 'J_Cornici_fin_2': 'J_Cornici_fin_2', 'J_Cornici_fin_3': 'J_Cornici_fin_3', 'J_Cornici_fin_4': 'J_Cornici_fin_4', 'J_Cornici_fin_5': 'J_Cornici_fin_5', 'K_Cornici_por_1': 'K_Cornici_por_1', 'K_Cornici_por_2': 'K_Cornici_por_2', 'K_Cornici_por_3': 'K_Cornici_por_3', 'K_Cornici_por_4': 'K_Cornici_por_4', 'L_Balc_strutt_1': 'L_Balc_strutt_1', 'L_Balc_strutt_2': 'L_Balc_strutt_2', 'M_Balc_par_1': 'M_Balc_par_1', 'M_Balc_par_2': 'M_Balc_par_2', 'N_Valore_1': 'N_Valore_1', 'N_Valore_2': 'N_Valore_2', 'O_Particolari_1': 'O_Particolari_1', 'O_Particolari_2': 'O_Particolari_2', 'O_Particolari_3': 'O_Particolari_3', 'P_Uso_edif_1': 'P_Uso_edif_1', 'P_Uso_edif_2': 'P_Uso_edif_2', 'Q_Ristrutt': 'Q_Ristrutt', 'T_Note_dem': 'T_Note_dem', 'U_Reti_tecn_1': 'U_Reti_tecn_1', 'U_Reti_tecn_2': 'U_Reti_tecn_2', 'V_Uso_area_1': 'V_Uso_area_1', 'V_Uso_area_2': 'V_Uso_area_2', 'V_Uso_area_3': 'V_Uso_area_3', 'stato': 'stato', 'GRADO D\'INTERVENTO': 'GRADO D\'INTERVENTO', 'PRESCRIZIONI': 'PRESCRIZIONI', 'VINCOLO AMBIENTALE': 'VINCOLO AMBIENTALE', 'scheda_agg': 'scheda_agg', 'Cat.2026': 'Cat.2026', 'pdf_web': 'pdf_web', 'html_link': 'html_link', });
lyr_Elementiartisticidipregiocornicimodanateaffreschifregi_4.set('fieldAliases', {'fid': 'fid', 'scheda': 'scheda', 'Stato_2025': 'Stato_2025', 'pdf_link': 'pdf_link', 'A_Solaio_1': 'A_Solaio_1', 'A_Solaio_2': 'A_Solaio_2', 'B_Copert_tipo_1': 'B_Copert_tipo_1', 'B_Copert_tipo_2': 'B_Copert_tipo_2', 'B_Copert_tipo_3': 'B_Copert_tipo_3', 'B_Copert_tipo_4': 'B_Copert_tipo_4', 'C_Copert_str_1': 'C_Copert_str_1', 'C_Copert_str_2': 'C_Copert_str_2', 'C_Copert_str_3': 'C_Copert_str_3', 'D_Gronda_1': 'D_Gronda_1', 'D_Gronda_2': 'D_Gronda_2', 'E_Pluv_can_1': 'E_Pluv_can_1', 'E_Pluv_can_2': 'E_Pluv_can_2', 'F_Muri_1': 'F_Muri_1', 'F_Muri_2': 'F_Muri_2', 'F_Muri_3': 'F_Muri_3', 'G_Finestre_1': 'G_Finestre_1', 'G_Finestre_2': 'G_Finestre_2', 'H_Oscuranti_1': 'H_Oscuranti_1', 'H_Oscuranti_2': 'H_Oscuranti_2', 'H_Oscuranti_3': 'H_Oscuranti_3', 'I_Porte_1': 'I_Porte_1', 'I_Porte_2': 'I_Porte_2', 'I_Porte_3': 'I_Porte_3', 'J_Cornici_fin_1': 'J_Cornici_fin_1', 'J_Cornici_fin_2': 'J_Cornici_fin_2', 'J_Cornici_fin_3': 'J_Cornici_fin_3', 'J_Cornici_fin_4': 'J_Cornici_fin_4', 'J_Cornici_fin_5': 'J_Cornici_fin_5', 'K_Cornici_por_1': 'K_Cornici_por_1', 'K_Cornici_por_2': 'K_Cornici_por_2', 'K_Cornici_por_3': 'K_Cornici_por_3', 'K_Cornici_por_4': 'K_Cornici_por_4', 'L_Balc_strutt_1': 'L_Balc_strutt_1', 'L_Balc_strutt_2': 'L_Balc_strutt_2', 'M_Balc_par_1': 'M_Balc_par_1', 'M_Balc_par_2': 'M_Balc_par_2', 'N_Valore_1': 'N_Valore_1', 'N_Valore_2': 'N_Valore_2', 'O_Particolari_1': 'O_Particolari_1', 'O_Particolari_2': 'O_Particolari_2', 'O_Particolari_3': 'O_Particolari_3', 'P_Uso_edif_1': 'P_Uso_edif_1', 'P_Uso_edif_2': 'P_Uso_edif_2', 'Q_Ristrutt': 'Q_Ristrutt', 'T_Note_dem': 'T_Note_dem', 'U_Reti_tecn_1': 'U_Reti_tecn_1', 'U_Reti_tecn_2': 'U_Reti_tecn_2', 'V_Uso_area_1': 'V_Uso_area_1', 'V_Uso_area_2': 'V_Uso_area_2', 'V_Uso_area_3': 'V_Uso_area_3', 'stato': 'stato', 'GRADO D\'INTERVENTO': 'GRADO D\'INTERVENTO', 'PRESCRIZIONI': 'PRESCRIZIONI', 'VINCOLO AMBIENTALE': 'VINCOLO AMBIENTALE', 'scheda_agg': 'scheda_agg', 'Cat.2026': 'Cat.2026', 'pdf_web': 'pdf_web', 'html_link': 'html_link', });
lyr_Aperturetrilitiche_5.set('fieldAliases', {'fid': 'fid', 'scheda': 'scheda', 'Stato_2025': 'Stato_2025', 'pdf_link': 'pdf_link', 'A_Solaio_1': 'A_Solaio_1', 'A_Solaio_2': 'A_Solaio_2', 'B_Copert_tipo_1': 'B_Copert_tipo_1', 'B_Copert_tipo_2': 'B_Copert_tipo_2', 'B_Copert_tipo_3': 'B_Copert_tipo_3', 'B_Copert_tipo_4': 'B_Copert_tipo_4', 'C_Copert_str_1': 'C_Copert_str_1', 'C_Copert_str_2': 'C_Copert_str_2', 'C_Copert_str_3': 'C_Copert_str_3', 'D_Gronda_1': 'D_Gronda_1', 'D_Gronda_2': 'D_Gronda_2', 'E_Pluv_can_1': 'E_Pluv_can_1', 'E_Pluv_can_2': 'E_Pluv_can_2', 'F_Muri_1': 'F_Muri_1', 'F_Muri_2': 'F_Muri_2', 'F_Muri_3': 'F_Muri_3', 'G_Finestre_1': 'G_Finestre_1', 'G_Finestre_2': 'G_Finestre_2', 'H_Oscuranti_1': 'H_Oscuranti_1', 'H_Oscuranti_2': 'H_Oscuranti_2', 'H_Oscuranti_3': 'H_Oscuranti_3', 'I_Porte_1': 'I_Porte_1', 'I_Porte_2': 'I_Porte_2', 'I_Porte_3': 'I_Porte_3', 'J_Cornici_fin_1': 'J_Cornici_fin_1', 'J_Cornici_fin_2': 'J_Cornici_fin_2', 'J_Cornici_fin_3': 'J_Cornici_fin_3', 'J_Cornici_fin_4': 'J_Cornici_fin_4', 'J_Cornici_fin_5': 'J_Cornici_fin_5', 'K_Cornici_por_1': 'K_Cornici_por_1', 'K_Cornici_por_2': 'K_Cornici_por_2', 'K_Cornici_por_3': 'K_Cornici_por_3', 'K_Cornici_por_4': 'K_Cornici_por_4', 'L_Balc_strutt_1': 'L_Balc_strutt_1', 'L_Balc_strutt_2': 'L_Balc_strutt_2', 'M_Balc_par_1': 'M_Balc_par_1', 'M_Balc_par_2': 'M_Balc_par_2', 'N_Valore_1': 'N_Valore_1', 'N_Valore_2': 'N_Valore_2', 'O_Particolari_1': 'O_Particolari_1', 'O_Particolari_2': 'O_Particolari_2', 'O_Particolari_3': 'O_Particolari_3', 'P_Uso_edif_1': 'P_Uso_edif_1', 'P_Uso_edif_2': 'P_Uso_edif_2', 'Q_Ristrutt': 'Q_Ristrutt', 'T_Note_dem': 'T_Note_dem', 'U_Reti_tecn_1': 'U_Reti_tecn_1', 'U_Reti_tecn_2': 'U_Reti_tecn_2', 'V_Uso_area_1': 'V_Uso_area_1', 'V_Uso_area_2': 'V_Uso_area_2', 'V_Uso_area_3': 'V_Uso_area_3', 'stato': 'stato', 'GRADO D\'INTERVENTO': 'GRADO D\'INTERVENTO', 'PRESCRIZIONI': 'PRESCRIZIONI', 'VINCOLO AMBIENTALE': 'VINCOLO AMBIENTALE', 'scheda_agg': 'scheda_agg', 'Cat.2026': 'Cat.2026', 'pdf_web': 'pdf_web', 'html_link': 'html_link', });
lyr_AperturetradizionaliaTconserramentoinlegno_6.set('fieldAliases', {'fid': 'fid', 'scheda': 'scheda', 'Stato_2025': 'Stato_2025', 'pdf_link': 'pdf_link', 'A_Solaio_1': 'A_Solaio_1', 'A_Solaio_2': 'A_Solaio_2', 'B_Copert_tipo_1': 'B_Copert_tipo_1', 'B_Copert_tipo_2': 'B_Copert_tipo_2', 'B_Copert_tipo_3': 'B_Copert_tipo_3', 'B_Copert_tipo_4': 'B_Copert_tipo_4', 'C_Copert_str_1': 'C_Copert_str_1', 'C_Copert_str_2': 'C_Copert_str_2', 'C_Copert_str_3': 'C_Copert_str_3', 'D_Gronda_1': 'D_Gronda_1', 'D_Gronda_2': 'D_Gronda_2', 'E_Pluv_can_1': 'E_Pluv_can_1', 'E_Pluv_can_2': 'E_Pluv_can_2', 'F_Muri_1': 'F_Muri_1', 'F_Muri_2': 'F_Muri_2', 'F_Muri_3': 'F_Muri_3', 'G_Finestre_1': 'G_Finestre_1', 'G_Finestre_2': 'G_Finestre_2', 'H_Oscuranti_1': 'H_Oscuranti_1', 'H_Oscuranti_2': 'H_Oscuranti_2', 'H_Oscuranti_3': 'H_Oscuranti_3', 'I_Porte_1': 'I_Porte_1', 'I_Porte_2': 'I_Porte_2', 'I_Porte_3': 'I_Porte_3', 'J_Cornici_fin_1': 'J_Cornici_fin_1', 'J_Cornici_fin_2': 'J_Cornici_fin_2', 'J_Cornici_fin_3': 'J_Cornici_fin_3', 'J_Cornici_fin_4': 'J_Cornici_fin_4', 'J_Cornici_fin_5': 'J_Cornici_fin_5', 'K_Cornici_por_1': 'K_Cornici_por_1', 'K_Cornici_por_2': 'K_Cornici_por_2', 'K_Cornici_por_3': 'K_Cornici_por_3', 'K_Cornici_por_4': 'K_Cornici_por_4', 'L_Balc_strutt_1': 'L_Balc_strutt_1', 'L_Balc_strutt_2': 'L_Balc_strutt_2', 'M_Balc_par_1': 'M_Balc_par_1', 'M_Balc_par_2': 'M_Balc_par_2', 'N_Valore_1': 'N_Valore_1', 'N_Valore_2': 'N_Valore_2', 'O_Particolari_1': 'O_Particolari_1', 'O_Particolari_2': 'O_Particolari_2', 'O_Particolari_3': 'O_Particolari_3', 'P_Uso_edif_1': 'P_Uso_edif_1', 'P_Uso_edif_2': 'P_Uso_edif_2', 'Q_Ristrutt': 'Q_Ristrutt', 'T_Note_dem': 'T_Note_dem', 'U_Reti_tecn_1': 'U_Reti_tecn_1', 'U_Reti_tecn_2': 'U_Reti_tecn_2', 'V_Uso_area_1': 'V_Uso_area_1', 'V_Uso_area_2': 'V_Uso_area_2', 'V_Uso_area_3': 'V_Uso_area_3', 'stato': 'stato', 'GRADO D\'INTERVENTO': 'GRADO D\'INTERVENTO', 'PRESCRIZIONI': 'PRESCRIZIONI', 'VINCOLO AMBIENTALE': 'VINCOLO AMBIENTALE', 'scheda_agg': 'scheda_agg', 'Cat.2026': 'Cat.2026', 'pdf_web': 'pdf_web', 'html_link': 'html_link', });
lyr_Tettoincoppidilaterizio_7.set('fieldAliases', {'fid': 'fid', 'scheda': 'scheda', 'Stato_2025': 'Stato_2025', 'pdf_link': 'pdf_link', 'A_Solaio_1': 'A_Solaio_1', 'A_Solaio_2': 'A_Solaio_2', 'B_Copert_tipo_1': 'B_Copert_tipo_1', 'B_Copert_tipo_2': 'B_Copert_tipo_2', 'B_Copert_tipo_3': 'B_Copert_tipo_3', 'B_Copert_tipo_4': 'B_Copert_tipo_4', 'C_Copert_str_1': 'C_Copert_str_1', 'C_Copert_str_2': 'C_Copert_str_2', 'C_Copert_str_3': 'C_Copert_str_3', 'D_Gronda_1': 'D_Gronda_1', 'D_Gronda_2': 'D_Gronda_2', 'E_Pluv_can_1': 'E_Pluv_can_1', 'E_Pluv_can_2': 'E_Pluv_can_2', 'F_Muri_1': 'F_Muri_1', 'F_Muri_2': 'F_Muri_2', 'F_Muri_3': 'F_Muri_3', 'G_Finestre_1': 'G_Finestre_1', 'G_Finestre_2': 'G_Finestre_2', 'H_Oscuranti_1': 'H_Oscuranti_1', 'H_Oscuranti_2': 'H_Oscuranti_2', 'H_Oscuranti_3': 'H_Oscuranti_3', 'I_Porte_1': 'I_Porte_1', 'I_Porte_2': 'I_Porte_2', 'I_Porte_3': 'I_Porte_3', 'J_Cornici_fin_1': 'J_Cornici_fin_1', 'J_Cornici_fin_2': 'J_Cornici_fin_2', 'J_Cornici_fin_3': 'J_Cornici_fin_3', 'J_Cornici_fin_4': 'J_Cornici_fin_4', 'J_Cornici_fin_5': 'J_Cornici_fin_5', 'K_Cornici_por_1': 'K_Cornici_por_1', 'K_Cornici_por_2': 'K_Cornici_por_2', 'K_Cornici_por_3': 'K_Cornici_por_3', 'K_Cornici_por_4': 'K_Cornici_por_4', 'L_Balc_strutt_1': 'L_Balc_strutt_1', 'L_Balc_strutt_2': 'L_Balc_strutt_2', 'M_Balc_par_1': 'M_Balc_par_1', 'M_Balc_par_2': 'M_Balc_par_2', 'N_Valore_1': 'N_Valore_1', 'N_Valore_2': 'N_Valore_2', 'O_Particolari_1': 'O_Particolari_1', 'O_Particolari_2': 'O_Particolari_2', 'O_Particolari_3': 'O_Particolari_3', 'P_Uso_edif_1': 'P_Uso_edif_1', 'P_Uso_edif_2': 'P_Uso_edif_2', 'Q_Ristrutt': 'Q_Ristrutt', 'T_Note_dem': 'T_Note_dem', 'U_Reti_tecn_1': 'U_Reti_tecn_1', 'U_Reti_tecn_2': 'U_Reti_tecn_2', 'V_Uso_area_1': 'V_Uso_area_1', 'V_Uso_area_2': 'V_Uso_area_2', 'V_Uso_area_3': 'V_Uso_area_3', 'stato': 'stato', 'GRADO D\'INTERVENTO': 'GRADO D\'INTERVENTO', 'PRESCRIZIONI': 'PRESCRIZIONI', 'VINCOLO AMBIENTALE': 'VINCOLO AMBIENTALE', 'scheda_agg': 'scheda_agg', 'Cat.2026': 'Cat.2026', 'pdf_web': 'pdf_web', 'html_link': 'html_link', });
lyr_Tettiinardesia_8.set('fieldAliases', {'fid': 'fid', 'scheda': 'scheda', 'Stato_2025': 'Stato_2025', 'pdf_link': 'pdf_link', 'A_Solaio_1': 'A_Solaio_1', 'A_Solaio_2': 'A_Solaio_2', 'B_Copert_tipo_1': 'B_Copert_tipo_1', 'B_Copert_tipo_2': 'B_Copert_tipo_2', 'B_Copert_tipo_3': 'B_Copert_tipo_3', 'B_Copert_tipo_4': 'B_Copert_tipo_4', 'C_Copert_str_1': 'C_Copert_str_1', 'C_Copert_str_2': 'C_Copert_str_2', 'C_Copert_str_3': 'C_Copert_str_3', 'D_Gronda_1': 'D_Gronda_1', 'D_Gronda_2': 'D_Gronda_2', 'E_Pluv_can_1': 'E_Pluv_can_1', 'E_Pluv_can_2': 'E_Pluv_can_2', 'F_Muri_1': 'F_Muri_1', 'F_Muri_2': 'F_Muri_2', 'F_Muri_3': 'F_Muri_3', 'G_Finestre_1': 'G_Finestre_1', 'G_Finestre_2': 'G_Finestre_2', 'H_Oscuranti_1': 'H_Oscuranti_1', 'H_Oscuranti_2': 'H_Oscuranti_2', 'H_Oscuranti_3': 'H_Oscuranti_3', 'I_Porte_1': 'I_Porte_1', 'I_Porte_2': 'I_Porte_2', 'I_Porte_3': 'I_Porte_3', 'J_Cornici_fin_1': 'J_Cornici_fin_1', 'J_Cornici_fin_2': 'J_Cornici_fin_2', 'J_Cornici_fin_3': 'J_Cornici_fin_3', 'J_Cornici_fin_4': 'J_Cornici_fin_4', 'J_Cornici_fin_5': 'J_Cornici_fin_5', 'K_Cornici_por_1': 'K_Cornici_por_1', 'K_Cornici_por_2': 'K_Cornici_por_2', 'K_Cornici_por_3': 'K_Cornici_por_3', 'K_Cornici_por_4': 'K_Cornici_por_4', 'L_Balc_strutt_1': 'L_Balc_strutt_1', 'L_Balc_strutt_2': 'L_Balc_strutt_2', 'M_Balc_par_1': 'M_Balc_par_1', 'M_Balc_par_2': 'M_Balc_par_2', 'N_Valore_1': 'N_Valore_1', 'N_Valore_2': 'N_Valore_2', 'O_Particolari_1': 'O_Particolari_1', 'O_Particolari_2': 'O_Particolari_2', 'O_Particolari_3': 'O_Particolari_3', 'P_Uso_edif_1': 'P_Uso_edif_1', 'P_Uso_edif_2': 'P_Uso_edif_2', 'Q_Ristrutt': 'Q_Ristrutt', 'T_Note_dem': 'T_Note_dem', 'U_Reti_tecn_1': 'U_Reti_tecn_1', 'U_Reti_tecn_2': 'U_Reti_tecn_2', 'V_Uso_area_1': 'V_Uso_area_1', 'V_Uso_area_2': 'V_Uso_area_2', 'V_Uso_area_3': 'V_Uso_area_3', 'stato': 'stato', 'GRADO D\'INTERVENTO': 'GRADO D\'INTERVENTO', 'PRESCRIZIONI': 'PRESCRIZIONI', 'VINCOLO AMBIENTALE': 'VINCOLO AMBIENTALE', 'scheda_agg': 'scheda_agg', 'Cat.2026': 'Cat.2026', 'pdf_web': 'pdf_web', 'html_link': 'html_link', });
lyr_Tettiinpiode_9.set('fieldAliases', {'fid': 'fid', 'scheda': 'scheda', 'Stato_2025': 'Stato_2025', 'pdf_link': 'pdf_link', 'A_Solaio_1': 'A_Solaio_1', 'A_Solaio_2': 'A_Solaio_2', 'B_Copert_tipo_1': 'B_Copert_tipo_1', 'B_Copert_tipo_2': 'B_Copert_tipo_2', 'B_Copert_tipo_3': 'B_Copert_tipo_3', 'B_Copert_tipo_4': 'B_Copert_tipo_4', 'C_Copert_str_1': 'C_Copert_str_1', 'C_Copert_str_2': 'C_Copert_str_2', 'C_Copert_str_3': 'C_Copert_str_3', 'D_Gronda_1': 'D_Gronda_1', 'D_Gronda_2': 'D_Gronda_2', 'E_Pluv_can_1': 'E_Pluv_can_1', 'E_Pluv_can_2': 'E_Pluv_can_2', 'F_Muri_1': 'F_Muri_1', 'F_Muri_2': 'F_Muri_2', 'F_Muri_3': 'F_Muri_3', 'G_Finestre_1': 'G_Finestre_1', 'G_Finestre_2': 'G_Finestre_2', 'H_Oscuranti_1': 'H_Oscuranti_1', 'H_Oscuranti_2': 'H_Oscuranti_2', 'H_Oscuranti_3': 'H_Oscuranti_3', 'I_Porte_1': 'I_Porte_1', 'I_Porte_2': 'I_Porte_2', 'I_Porte_3': 'I_Porte_3', 'J_Cornici_fin_1': 'J_Cornici_fin_1', 'J_Cornici_fin_2': 'J_Cornici_fin_2', 'J_Cornici_fin_3': 'J_Cornici_fin_3', 'J_Cornici_fin_4': 'J_Cornici_fin_4', 'J_Cornici_fin_5': 'J_Cornici_fin_5', 'K_Cornici_por_1': 'K_Cornici_por_1', 'K_Cornici_por_2': 'K_Cornici_por_2', 'K_Cornici_por_3': 'K_Cornici_por_3', 'K_Cornici_por_4': 'K_Cornici_por_4', 'L_Balc_strutt_1': 'L_Balc_strutt_1', 'L_Balc_strutt_2': 'L_Balc_strutt_2', 'M_Balc_par_1': 'M_Balc_par_1', 'M_Balc_par_2': 'M_Balc_par_2', 'N_Valore_1': 'N_Valore_1', 'N_Valore_2': 'N_Valore_2', 'O_Particolari_1': 'O_Particolari_1', 'O_Particolari_2': 'O_Particolari_2', 'O_Particolari_3': 'O_Particolari_3', 'P_Uso_edif_1': 'P_Uso_edif_1', 'P_Uso_edif_2': 'P_Uso_edif_2', 'Q_Ristrutt': 'Q_Ristrutt', 'T_Note_dem': 'T_Note_dem', 'U_Reti_tecn_1': 'U_Reti_tecn_1', 'U_Reti_tecn_2': 'U_Reti_tecn_2', 'V_Uso_area_1': 'V_Uso_area_1', 'V_Uso_area_2': 'V_Uso_area_2', 'V_Uso_area_3': 'V_Uso_area_3', 'stato': 'stato', 'GRADO D\'INTERVENTO': 'GRADO D\'INTERVENTO', 'PRESCRIZIONI': 'PRESCRIZIONI', 'VINCOLO AMBIENTALE': 'VINCOLO AMBIENTALE', 'scheda_agg': 'scheda_agg', 'Cat.2026': 'Cat.2026', 'pdf_web': 'pdf_web', 'html_link': 'html_link', });
lyr_Edificischedati_10.set('fieldAliases', {'fid': 'fid', 'scheda': 'scheda', 'Stato_2025': 'Stato_2025', 'pdf_link': 'pdf_link', 'A_Solaio_1': 'A_Solaio_1', 'A_Solaio_2': 'A_Solaio_2', 'B_Copert_tipo_1': 'B_Copert_tipo_1', 'B_Copert_tipo_2': 'B_Copert_tipo_2', 'B_Copert_tipo_3': 'B_Copert_tipo_3', 'B_Copert_tipo_4': 'B_Copert_tipo_4', 'C_Copert_str_1': 'C_Copert_str_1', 'C_Copert_str_2': 'C_Copert_str_2', 'C_Copert_str_3': 'C_Copert_str_3', 'D_Gronda_1': 'D_Gronda_1', 'D_Gronda_2': 'D_Gronda_2', 'E_Pluv_can_1': 'E_Pluv_can_1', 'E_Pluv_can_2': 'E_Pluv_can_2', 'F_Muri_1': 'F_Muri_1', 'F_Muri_2': 'F_Muri_2', 'F_Muri_3': 'F_Muri_3', 'G_Finestre_1': 'G_Finestre_1', 'G_Finestre_2': 'G_Finestre_2', 'H_Oscuranti_1': 'H_Oscuranti_1', 'H_Oscuranti_2': 'H_Oscuranti_2', 'H_Oscuranti_3': 'H_Oscuranti_3', 'I_Porte_1': 'I_Porte_1', 'I_Porte_2': 'I_Porte_2', 'I_Porte_3': 'I_Porte_3', 'J_Cornici_fin_1': 'J_Cornici_fin_1', 'J_Cornici_fin_2': 'J_Cornici_fin_2', 'J_Cornici_fin_3': 'J_Cornici_fin_3', 'J_Cornici_fin_4': 'J_Cornici_fin_4', 'J_Cornici_fin_5': 'J_Cornici_fin_5', 'K_Cornici_por_1': 'K_Cornici_por_1', 'K_Cornici_por_2': 'K_Cornici_por_2', 'K_Cornici_por_3': 'K_Cornici_por_3', 'K_Cornici_por_4': 'K_Cornici_por_4', 'L_Balc_strutt_1': 'L_Balc_strutt_1', 'L_Balc_strutt_2': 'L_Balc_strutt_2', 'M_Balc_par_1': 'M_Balc_par_1', 'M_Balc_par_2': 'M_Balc_par_2', 'N_Valore_1': 'N_Valore_1', 'N_Valore_2': 'N_Valore_2', 'O_Particolari_1': 'O_Particolari_1', 'O_Particolari_2': 'O_Particolari_2', 'O_Particolari_3': 'O_Particolari_3', 'P_Uso_edif_1': 'P_Uso_edif_1', 'P_Uso_edif_2': 'P_Uso_edif_2', 'Q_Ristrutt': 'Q_Ristrutt', 'T_Note_dem': 'T_Note_dem', 'U_Reti_tecn_1': 'U_Reti_tecn_1', 'U_Reti_tecn_2': 'U_Reti_tecn_2', 'V_Uso_area_1': 'V_Uso_area_1', 'V_Uso_area_2': 'V_Uso_area_2', 'V_Uso_area_3': 'V_Uso_area_3', 'stato': 'stato', 'GRADO D\'INTERVENTO': 'GRADO D\'INTERVENTO', 'PRESCRIZIONI': 'PRESCRIZIONI', 'VINCOLO AMBIENTALE': 'VINCOLO AMBIENTALE', 'scheda_agg': 'scheda_agg', 'Cat.2026': 'Cat.2026', 'pdf_web': 'pdf_web', 'html_link': 'html_link', });
lyr_Confinecomunale_11.set('fieldAliases', {'fid': 'fid', 'OBJECTID': 'OBJECTID', 'CLASSREF': 'CLASSREF', 'BELFIORE': 'BELFIORE', 'COD_ISTATN': 'COD_ISTATN', 'NOME_COM': 'NOME_COM', 'COD_PRO': 'COD_PRO', 'NOME_PRO': 'NOME_PRO', 'SIG_PRO': 'SIG_PRO', 'COD_CMO': 'COD_CMO', 'NOME_CMO': 'NOME_CMO', 'COD_ASL': 'COD_ASL', 'NOME_ASL': 'NOME_ASL', 'COD_REG': 'COD_REG', 'NOME_REG': 'NOME_REG', 'ANNO': 'ANNO', 'ISTAT': 'ISTAT', 'LEGGE_ISTI': 'LEGGE_ISTI', 'ATS_COD': 'ATS_COD', 'ATS_DEC': 'ATS_DEC', 'CMETR_COD': 'CMETR_COD', 'CMETR_DEC': 'CMETR_DEC', 'SHAPE_AREA': 'SHAPE_AREA', 'SHAPE_LEN': 'SHAPE_LEN', });
lyr_Sentieri_2.set('fieldImages', {'fid': '', 'tipo': '', 'Numero CAI sentiero': '', });
lyr_Capriateligneedirilievoartistico_3.set('fieldImages', {'fid': 'TextEdit', 'scheda': 'TextEdit', 'Stato_2025': 'Range', 'pdf_link': 'TextEdit', 'A_Solaio_1': 'TextEdit', 'A_Solaio_2': 'TextEdit', 'B_Copert_tipo_1': 'TextEdit', 'B_Copert_tipo_2': 'TextEdit', 'B_Copert_tipo_3': 'TextEdit', 'B_Copert_tipo_4': 'TextEdit', 'C_Copert_str_1': 'TextEdit', 'C_Copert_str_2': 'TextEdit', 'C_Copert_str_3': 'TextEdit', 'D_Gronda_1': 'TextEdit', 'D_Gronda_2': 'TextEdit', 'E_Pluv_can_1': 'TextEdit', 'E_Pluv_can_2': 'TextEdit', 'F_Muri_1': 'TextEdit', 'F_Muri_2': 'TextEdit', 'F_Muri_3': 'TextEdit', 'G_Finestre_1': 'TextEdit', 'G_Finestre_2': 'TextEdit', 'H_Oscuranti_1': 'TextEdit', 'H_Oscuranti_2': 'TextEdit', 'H_Oscuranti_3': 'TextEdit', 'I_Porte_1': 'TextEdit', 'I_Porte_2': 'TextEdit', 'I_Porte_3': 'TextEdit', 'J_Cornici_fin_1': 'TextEdit', 'J_Cornici_fin_2': 'TextEdit', 'J_Cornici_fin_3': 'TextEdit', 'J_Cornici_fin_4': 'TextEdit', 'J_Cornici_fin_5': 'TextEdit', 'K_Cornici_por_1': 'TextEdit', 'K_Cornici_por_2': 'TextEdit', 'K_Cornici_por_3': 'TextEdit', 'K_Cornici_por_4': 'TextEdit', 'L_Balc_strutt_1': 'TextEdit', 'L_Balc_strutt_2': 'TextEdit', 'M_Balc_par_1': 'TextEdit', 'M_Balc_par_2': 'TextEdit', 'N_Valore_1': 'TextEdit', 'N_Valore_2': 'TextEdit', 'O_Particolari_1': 'TextEdit', 'O_Particolari_2': 'TextEdit', 'O_Particolari_3': 'TextEdit', 'P_Uso_edif_1': 'TextEdit', 'P_Uso_edif_2': 'TextEdit', 'Q_Ristrutt': 'TextEdit', 'T_Note_dem': 'TextEdit', 'U_Reti_tecn_1': 'TextEdit', 'U_Reti_tecn_2': 'TextEdit', 'V_Uso_area_1': 'TextEdit', 'V_Uso_area_2': 'TextEdit', 'V_Uso_area_3': 'TextEdit', 'stato': 'TextEdit', 'GRADO D\'INTERVENTO': 'TextEdit', 'PRESCRIZIONI': 'TextEdit', 'VINCOLO AMBIENTALE': 'TextEdit', 'scheda_agg': 'TextEdit', 'Cat.2026': 'TextEdit', 'pdf_web': 'TextEdit', 'html_link': 'TextEdit', });
lyr_Elementiartisticidipregiocornicimodanateaffreschifregi_4.set('fieldImages', {'fid': 'TextEdit', 'scheda': 'TextEdit', 'Stato_2025': 'Range', 'pdf_link': 'TextEdit', 'A_Solaio_1': 'TextEdit', 'A_Solaio_2': 'TextEdit', 'B_Copert_tipo_1': 'TextEdit', 'B_Copert_tipo_2': 'TextEdit', 'B_Copert_tipo_3': 'TextEdit', 'B_Copert_tipo_4': 'TextEdit', 'C_Copert_str_1': 'TextEdit', 'C_Copert_str_2': 'TextEdit', 'C_Copert_str_3': 'TextEdit', 'D_Gronda_1': 'TextEdit', 'D_Gronda_2': 'TextEdit', 'E_Pluv_can_1': 'TextEdit', 'E_Pluv_can_2': 'TextEdit', 'F_Muri_1': 'TextEdit', 'F_Muri_2': 'TextEdit', 'F_Muri_3': 'TextEdit', 'G_Finestre_1': 'TextEdit', 'G_Finestre_2': 'TextEdit', 'H_Oscuranti_1': 'TextEdit', 'H_Oscuranti_2': 'TextEdit', 'H_Oscuranti_3': 'TextEdit', 'I_Porte_1': 'TextEdit', 'I_Porte_2': 'TextEdit', 'I_Porte_3': 'TextEdit', 'J_Cornici_fin_1': 'TextEdit', 'J_Cornici_fin_2': 'TextEdit', 'J_Cornici_fin_3': 'TextEdit', 'J_Cornici_fin_4': 'TextEdit', 'J_Cornici_fin_5': 'TextEdit', 'K_Cornici_por_1': 'TextEdit', 'K_Cornici_por_2': 'TextEdit', 'K_Cornici_por_3': 'TextEdit', 'K_Cornici_por_4': 'TextEdit', 'L_Balc_strutt_1': 'TextEdit', 'L_Balc_strutt_2': 'TextEdit', 'M_Balc_par_1': 'TextEdit', 'M_Balc_par_2': 'TextEdit', 'N_Valore_1': 'TextEdit', 'N_Valore_2': 'TextEdit', 'O_Particolari_1': 'TextEdit', 'O_Particolari_2': 'TextEdit', 'O_Particolari_3': 'TextEdit', 'P_Uso_edif_1': 'TextEdit', 'P_Uso_edif_2': 'TextEdit', 'Q_Ristrutt': 'TextEdit', 'T_Note_dem': 'TextEdit', 'U_Reti_tecn_1': 'TextEdit', 'U_Reti_tecn_2': 'TextEdit', 'V_Uso_area_1': 'TextEdit', 'V_Uso_area_2': 'TextEdit', 'V_Uso_area_3': 'TextEdit', 'stato': 'TextEdit', 'GRADO D\'INTERVENTO': 'TextEdit', 'PRESCRIZIONI': 'TextEdit', 'VINCOLO AMBIENTALE': 'TextEdit', 'scheda_agg': 'TextEdit', 'Cat.2026': 'TextEdit', 'pdf_web': 'TextEdit', 'html_link': 'TextEdit', });
lyr_Aperturetrilitiche_5.set('fieldImages', {'fid': 'TextEdit', 'scheda': 'TextEdit', 'Stato_2025': 'Range', 'pdf_link': 'TextEdit', 'A_Solaio_1': 'TextEdit', 'A_Solaio_2': 'TextEdit', 'B_Copert_tipo_1': 'TextEdit', 'B_Copert_tipo_2': 'TextEdit', 'B_Copert_tipo_3': 'TextEdit', 'B_Copert_tipo_4': 'TextEdit', 'C_Copert_str_1': 'TextEdit', 'C_Copert_str_2': 'TextEdit', 'C_Copert_str_3': 'TextEdit', 'D_Gronda_1': 'TextEdit', 'D_Gronda_2': 'TextEdit', 'E_Pluv_can_1': 'TextEdit', 'E_Pluv_can_2': 'TextEdit', 'F_Muri_1': 'TextEdit', 'F_Muri_2': 'TextEdit', 'F_Muri_3': 'TextEdit', 'G_Finestre_1': 'TextEdit', 'G_Finestre_2': 'TextEdit', 'H_Oscuranti_1': 'TextEdit', 'H_Oscuranti_2': 'TextEdit', 'H_Oscuranti_3': 'TextEdit', 'I_Porte_1': 'TextEdit', 'I_Porte_2': 'TextEdit', 'I_Porte_3': 'TextEdit', 'J_Cornici_fin_1': 'TextEdit', 'J_Cornici_fin_2': 'TextEdit', 'J_Cornici_fin_3': 'TextEdit', 'J_Cornici_fin_4': 'TextEdit', 'J_Cornici_fin_5': 'TextEdit', 'K_Cornici_por_1': 'TextEdit', 'K_Cornici_por_2': 'TextEdit', 'K_Cornici_por_3': 'TextEdit', 'K_Cornici_por_4': 'TextEdit', 'L_Balc_strutt_1': 'TextEdit', 'L_Balc_strutt_2': 'TextEdit', 'M_Balc_par_1': 'TextEdit', 'M_Balc_par_2': 'TextEdit', 'N_Valore_1': 'TextEdit', 'N_Valore_2': 'TextEdit', 'O_Particolari_1': 'TextEdit', 'O_Particolari_2': 'TextEdit', 'O_Particolari_3': 'TextEdit', 'P_Uso_edif_1': 'TextEdit', 'P_Uso_edif_2': 'TextEdit', 'Q_Ristrutt': 'TextEdit', 'T_Note_dem': 'TextEdit', 'U_Reti_tecn_1': 'TextEdit', 'U_Reti_tecn_2': 'TextEdit', 'V_Uso_area_1': 'TextEdit', 'V_Uso_area_2': 'TextEdit', 'V_Uso_area_3': 'TextEdit', 'stato': 'TextEdit', 'GRADO D\'INTERVENTO': 'TextEdit', 'PRESCRIZIONI': 'TextEdit', 'VINCOLO AMBIENTALE': 'TextEdit', 'scheda_agg': 'TextEdit', 'Cat.2026': 'TextEdit', 'pdf_web': 'TextEdit', 'html_link': 'TextEdit', });
lyr_AperturetradizionaliaTconserramentoinlegno_6.set('fieldImages', {'fid': 'TextEdit', 'scheda': 'TextEdit', 'Stato_2025': 'Range', 'pdf_link': 'TextEdit', 'A_Solaio_1': 'TextEdit', 'A_Solaio_2': 'TextEdit', 'B_Copert_tipo_1': 'TextEdit', 'B_Copert_tipo_2': 'TextEdit', 'B_Copert_tipo_3': 'TextEdit', 'B_Copert_tipo_4': 'TextEdit', 'C_Copert_str_1': 'TextEdit', 'C_Copert_str_2': 'TextEdit', 'C_Copert_str_3': 'TextEdit', 'D_Gronda_1': 'TextEdit', 'D_Gronda_2': 'TextEdit', 'E_Pluv_can_1': 'TextEdit', 'E_Pluv_can_2': 'TextEdit', 'F_Muri_1': 'TextEdit', 'F_Muri_2': 'TextEdit', 'F_Muri_3': 'TextEdit', 'G_Finestre_1': 'TextEdit', 'G_Finestre_2': 'TextEdit', 'H_Oscuranti_1': 'TextEdit', 'H_Oscuranti_2': 'TextEdit', 'H_Oscuranti_3': 'TextEdit', 'I_Porte_1': 'TextEdit', 'I_Porte_2': 'TextEdit', 'I_Porte_3': 'TextEdit', 'J_Cornici_fin_1': 'TextEdit', 'J_Cornici_fin_2': 'TextEdit', 'J_Cornici_fin_3': 'TextEdit', 'J_Cornici_fin_4': 'TextEdit', 'J_Cornici_fin_5': 'TextEdit', 'K_Cornici_por_1': 'TextEdit', 'K_Cornici_por_2': 'TextEdit', 'K_Cornici_por_3': 'TextEdit', 'K_Cornici_por_4': 'TextEdit', 'L_Balc_strutt_1': 'TextEdit', 'L_Balc_strutt_2': 'TextEdit', 'M_Balc_par_1': 'TextEdit', 'M_Balc_par_2': 'TextEdit', 'N_Valore_1': 'TextEdit', 'N_Valore_2': 'TextEdit', 'O_Particolari_1': 'TextEdit', 'O_Particolari_2': 'TextEdit', 'O_Particolari_3': 'TextEdit', 'P_Uso_edif_1': 'TextEdit', 'P_Uso_edif_2': 'TextEdit', 'Q_Ristrutt': 'TextEdit', 'T_Note_dem': 'TextEdit', 'U_Reti_tecn_1': 'TextEdit', 'U_Reti_tecn_2': 'TextEdit', 'V_Uso_area_1': 'TextEdit', 'V_Uso_area_2': 'TextEdit', 'V_Uso_area_3': 'TextEdit', 'stato': 'TextEdit', 'GRADO D\'INTERVENTO': 'TextEdit', 'PRESCRIZIONI': 'TextEdit', 'VINCOLO AMBIENTALE': 'TextEdit', 'scheda_agg': 'TextEdit', 'Cat.2026': 'TextEdit', 'pdf_web': 'TextEdit', 'html_link': 'TextEdit', });
lyr_Tettoincoppidilaterizio_7.set('fieldImages', {'fid': 'TextEdit', 'scheda': 'TextEdit', 'Stato_2025': 'Range', 'pdf_link': 'TextEdit', 'A_Solaio_1': 'TextEdit', 'A_Solaio_2': 'TextEdit', 'B_Copert_tipo_1': 'TextEdit', 'B_Copert_tipo_2': 'TextEdit', 'B_Copert_tipo_3': 'TextEdit', 'B_Copert_tipo_4': 'TextEdit', 'C_Copert_str_1': 'TextEdit', 'C_Copert_str_2': 'TextEdit', 'C_Copert_str_3': 'TextEdit', 'D_Gronda_1': 'TextEdit', 'D_Gronda_2': 'TextEdit', 'E_Pluv_can_1': 'TextEdit', 'E_Pluv_can_2': 'TextEdit', 'F_Muri_1': 'TextEdit', 'F_Muri_2': 'TextEdit', 'F_Muri_3': 'TextEdit', 'G_Finestre_1': 'TextEdit', 'G_Finestre_2': 'TextEdit', 'H_Oscuranti_1': 'TextEdit', 'H_Oscuranti_2': 'TextEdit', 'H_Oscuranti_3': 'TextEdit', 'I_Porte_1': 'TextEdit', 'I_Porte_2': 'TextEdit', 'I_Porte_3': 'TextEdit', 'J_Cornici_fin_1': 'TextEdit', 'J_Cornici_fin_2': 'TextEdit', 'J_Cornici_fin_3': 'TextEdit', 'J_Cornici_fin_4': 'TextEdit', 'J_Cornici_fin_5': 'TextEdit', 'K_Cornici_por_1': 'TextEdit', 'K_Cornici_por_2': 'TextEdit', 'K_Cornici_por_3': 'TextEdit', 'K_Cornici_por_4': 'TextEdit', 'L_Balc_strutt_1': 'TextEdit', 'L_Balc_strutt_2': 'TextEdit', 'M_Balc_par_1': 'TextEdit', 'M_Balc_par_2': 'TextEdit', 'N_Valore_1': 'TextEdit', 'N_Valore_2': 'TextEdit', 'O_Particolari_1': 'TextEdit', 'O_Particolari_2': 'TextEdit', 'O_Particolari_3': 'TextEdit', 'P_Uso_edif_1': 'TextEdit', 'P_Uso_edif_2': 'TextEdit', 'Q_Ristrutt': 'TextEdit', 'T_Note_dem': 'TextEdit', 'U_Reti_tecn_1': 'TextEdit', 'U_Reti_tecn_2': 'TextEdit', 'V_Uso_area_1': 'TextEdit', 'V_Uso_area_2': 'TextEdit', 'V_Uso_area_3': 'TextEdit', 'stato': 'TextEdit', 'GRADO D\'INTERVENTO': 'TextEdit', 'PRESCRIZIONI': 'TextEdit', 'VINCOLO AMBIENTALE': 'TextEdit', 'scheda_agg': 'TextEdit', 'Cat.2026': 'TextEdit', 'pdf_web': 'TextEdit', 'html_link': 'TextEdit', });
lyr_Tettiinardesia_8.set('fieldImages', {'fid': 'TextEdit', 'scheda': 'TextEdit', 'Stato_2025': 'Range', 'pdf_link': 'TextEdit', 'A_Solaio_1': 'TextEdit', 'A_Solaio_2': 'TextEdit', 'B_Copert_tipo_1': 'TextEdit', 'B_Copert_tipo_2': 'TextEdit', 'B_Copert_tipo_3': 'TextEdit', 'B_Copert_tipo_4': 'TextEdit', 'C_Copert_str_1': 'TextEdit', 'C_Copert_str_2': 'TextEdit', 'C_Copert_str_3': 'TextEdit', 'D_Gronda_1': 'TextEdit', 'D_Gronda_2': 'TextEdit', 'E_Pluv_can_1': 'TextEdit', 'E_Pluv_can_2': 'TextEdit', 'F_Muri_1': 'TextEdit', 'F_Muri_2': 'TextEdit', 'F_Muri_3': 'TextEdit', 'G_Finestre_1': 'TextEdit', 'G_Finestre_2': 'TextEdit', 'H_Oscuranti_1': 'TextEdit', 'H_Oscuranti_2': 'TextEdit', 'H_Oscuranti_3': 'TextEdit', 'I_Porte_1': 'TextEdit', 'I_Porte_2': 'TextEdit', 'I_Porte_3': 'TextEdit', 'J_Cornici_fin_1': 'TextEdit', 'J_Cornici_fin_2': 'TextEdit', 'J_Cornici_fin_3': 'TextEdit', 'J_Cornici_fin_4': 'TextEdit', 'J_Cornici_fin_5': 'TextEdit', 'K_Cornici_por_1': 'TextEdit', 'K_Cornici_por_2': 'TextEdit', 'K_Cornici_por_3': 'TextEdit', 'K_Cornici_por_4': 'TextEdit', 'L_Balc_strutt_1': 'TextEdit', 'L_Balc_strutt_2': 'TextEdit', 'M_Balc_par_1': 'TextEdit', 'M_Balc_par_2': 'TextEdit', 'N_Valore_1': 'TextEdit', 'N_Valore_2': 'TextEdit', 'O_Particolari_1': 'TextEdit', 'O_Particolari_2': 'TextEdit', 'O_Particolari_3': 'TextEdit', 'P_Uso_edif_1': 'TextEdit', 'P_Uso_edif_2': 'TextEdit', 'Q_Ristrutt': 'TextEdit', 'T_Note_dem': 'TextEdit', 'U_Reti_tecn_1': 'TextEdit', 'U_Reti_tecn_2': 'TextEdit', 'V_Uso_area_1': 'TextEdit', 'V_Uso_area_2': 'TextEdit', 'V_Uso_area_3': 'TextEdit', 'stato': 'TextEdit', 'GRADO D\'INTERVENTO': 'TextEdit', 'PRESCRIZIONI': 'TextEdit', 'VINCOLO AMBIENTALE': 'TextEdit', 'scheda_agg': 'TextEdit', 'Cat.2026': 'TextEdit', 'pdf_web': 'TextEdit', 'html_link': 'TextEdit', });
lyr_Tettiinpiode_9.set('fieldImages', {'fid': 'TextEdit', 'scheda': 'TextEdit', 'Stato_2025': 'Range', 'pdf_link': 'TextEdit', 'A_Solaio_1': 'TextEdit', 'A_Solaio_2': 'TextEdit', 'B_Copert_tipo_1': 'TextEdit', 'B_Copert_tipo_2': 'TextEdit', 'B_Copert_tipo_3': 'TextEdit', 'B_Copert_tipo_4': 'TextEdit', 'C_Copert_str_1': 'TextEdit', 'C_Copert_str_2': 'TextEdit', 'C_Copert_str_3': 'TextEdit', 'D_Gronda_1': 'TextEdit', 'D_Gronda_2': 'TextEdit', 'E_Pluv_can_1': 'TextEdit', 'E_Pluv_can_2': 'TextEdit', 'F_Muri_1': 'TextEdit', 'F_Muri_2': 'TextEdit', 'F_Muri_3': 'TextEdit', 'G_Finestre_1': 'TextEdit', 'G_Finestre_2': 'TextEdit', 'H_Oscuranti_1': 'TextEdit', 'H_Oscuranti_2': 'TextEdit', 'H_Oscuranti_3': 'TextEdit', 'I_Porte_1': 'TextEdit', 'I_Porte_2': 'TextEdit', 'I_Porte_3': 'TextEdit', 'J_Cornici_fin_1': 'TextEdit', 'J_Cornici_fin_2': 'TextEdit', 'J_Cornici_fin_3': 'TextEdit', 'J_Cornici_fin_4': 'TextEdit', 'J_Cornici_fin_5': 'TextEdit', 'K_Cornici_por_1': 'TextEdit', 'K_Cornici_por_2': 'TextEdit', 'K_Cornici_por_3': 'TextEdit', 'K_Cornici_por_4': 'TextEdit', 'L_Balc_strutt_1': 'TextEdit', 'L_Balc_strutt_2': 'TextEdit', 'M_Balc_par_1': 'TextEdit', 'M_Balc_par_2': 'TextEdit', 'N_Valore_1': 'TextEdit', 'N_Valore_2': 'TextEdit', 'O_Particolari_1': 'TextEdit', 'O_Particolari_2': 'TextEdit', 'O_Particolari_3': 'TextEdit', 'P_Uso_edif_1': 'TextEdit', 'P_Uso_edif_2': 'TextEdit', 'Q_Ristrutt': 'TextEdit', 'T_Note_dem': 'TextEdit', 'U_Reti_tecn_1': 'TextEdit', 'U_Reti_tecn_2': 'TextEdit', 'V_Uso_area_1': 'TextEdit', 'V_Uso_area_2': 'TextEdit', 'V_Uso_area_3': 'TextEdit', 'stato': 'TextEdit', 'GRADO D\'INTERVENTO': 'TextEdit', 'PRESCRIZIONI': 'TextEdit', 'VINCOLO AMBIENTALE': 'TextEdit', 'scheda_agg': 'TextEdit', 'Cat.2026': 'TextEdit', 'pdf_web': 'TextEdit', 'html_link': 'TextEdit', });
lyr_Edificischedati_10.set('fieldImages', {'fid': 'TextEdit', 'scheda': 'TextEdit', 'Stato_2025': 'Range', 'pdf_link': 'TextEdit', 'A_Solaio_1': 'TextEdit', 'A_Solaio_2': 'TextEdit', 'B_Copert_tipo_1': 'TextEdit', 'B_Copert_tipo_2': 'TextEdit', 'B_Copert_tipo_3': 'TextEdit', 'B_Copert_tipo_4': 'TextEdit', 'C_Copert_str_1': 'TextEdit', 'C_Copert_str_2': 'TextEdit', 'C_Copert_str_3': 'TextEdit', 'D_Gronda_1': 'TextEdit', 'D_Gronda_2': 'TextEdit', 'E_Pluv_can_1': 'TextEdit', 'E_Pluv_can_2': 'TextEdit', 'F_Muri_1': 'TextEdit', 'F_Muri_2': 'TextEdit', 'F_Muri_3': 'TextEdit', 'G_Finestre_1': 'TextEdit', 'G_Finestre_2': 'TextEdit', 'H_Oscuranti_1': 'TextEdit', 'H_Oscuranti_2': 'TextEdit', 'H_Oscuranti_3': 'TextEdit', 'I_Porte_1': 'TextEdit', 'I_Porte_2': 'TextEdit', 'I_Porte_3': 'TextEdit', 'J_Cornici_fin_1': 'TextEdit', 'J_Cornici_fin_2': 'TextEdit', 'J_Cornici_fin_3': 'TextEdit', 'J_Cornici_fin_4': 'TextEdit', 'J_Cornici_fin_5': 'TextEdit', 'K_Cornici_por_1': 'TextEdit', 'K_Cornici_por_2': 'TextEdit', 'K_Cornici_por_3': 'TextEdit', 'K_Cornici_por_4': 'TextEdit', 'L_Balc_strutt_1': 'TextEdit', 'L_Balc_strutt_2': 'TextEdit', 'M_Balc_par_1': 'TextEdit', 'M_Balc_par_2': 'TextEdit', 'N_Valore_1': 'TextEdit', 'N_Valore_2': 'TextEdit', 'O_Particolari_1': 'TextEdit', 'O_Particolari_2': 'TextEdit', 'O_Particolari_3': 'TextEdit', 'P_Uso_edif_1': 'TextEdit', 'P_Uso_edif_2': 'TextEdit', 'Q_Ristrutt': 'TextEdit', 'T_Note_dem': 'TextEdit', 'U_Reti_tecn_1': 'TextEdit', 'U_Reti_tecn_2': 'TextEdit', 'V_Uso_area_1': 'TextEdit', 'V_Uso_area_2': 'TextEdit', 'V_Uso_area_3': 'TextEdit', 'stato': 'TextEdit', 'GRADO D\'INTERVENTO': 'TextEdit', 'PRESCRIZIONI': 'TextEdit', 'VINCOLO AMBIENTALE': 'TextEdit', 'scheda_agg': 'TextEdit', 'Cat.2026': 'TextEdit', 'pdf_web': 'TextEdit', 'html_link': 'TextEdit', });
lyr_Confinecomunale_11.set('fieldImages', {'fid': '', 'OBJECTID': '', 'CLASSREF': '', 'BELFIORE': '', 'COD_ISTATN': '', 'NOME_COM': '', 'COD_PRO': '', 'NOME_PRO': '', 'SIG_PRO': '', 'COD_CMO': '', 'NOME_CMO': '', 'COD_ASL': '', 'NOME_ASL': '', 'COD_REG': '', 'NOME_REG': '', 'ANNO': '', 'ISTAT': '', 'LEGGE_ISTI': '', 'ATS_COD': '', 'ATS_DEC': '', 'CMETR_COD': '', 'CMETR_DEC': '', 'SHAPE_AREA': '', 'SHAPE_LEN': '', });
lyr_Sentieri_2.set('fieldLabels', {'fid': 'no label', 'tipo': 'no label', 'Numero CAI sentiero': 'no label', });
lyr_Capriateligneedirilievoartistico_3.set('fieldLabels', {'fid': 'no label', 'scheda': 'no label', 'Stato_2025': 'no label', 'pdf_link': 'no label', 'A_Solaio_1': 'no label', 'A_Solaio_2': 'no label', 'B_Copert_tipo_1': 'no label', 'B_Copert_tipo_2': 'no label', 'B_Copert_tipo_3': 'no label', 'B_Copert_tipo_4': 'no label', 'C_Copert_str_1': 'no label', 'C_Copert_str_2': 'no label', 'C_Copert_str_3': 'no label', 'D_Gronda_1': 'no label', 'D_Gronda_2': 'no label', 'E_Pluv_can_1': 'no label', 'E_Pluv_can_2': 'no label', 'F_Muri_1': 'no label', 'F_Muri_2': 'no label', 'F_Muri_3': 'no label', 'G_Finestre_1': 'no label', 'G_Finestre_2': 'no label', 'H_Oscuranti_1': 'no label', 'H_Oscuranti_2': 'no label', 'H_Oscuranti_3': 'no label', 'I_Porte_1': 'no label', 'I_Porte_2': 'no label', 'I_Porte_3': 'no label', 'J_Cornici_fin_1': 'no label', 'J_Cornici_fin_2': 'no label', 'J_Cornici_fin_3': 'no label', 'J_Cornici_fin_4': 'no label', 'J_Cornici_fin_5': 'no label', 'K_Cornici_por_1': 'no label', 'K_Cornici_por_2': 'no label', 'K_Cornici_por_3': 'no label', 'K_Cornici_por_4': 'no label', 'L_Balc_strutt_1': 'no label', 'L_Balc_strutt_2': 'no label', 'M_Balc_par_1': 'no label', 'M_Balc_par_2': 'no label', 'N_Valore_1': 'no label', 'N_Valore_2': 'no label', 'O_Particolari_1': 'no label', 'O_Particolari_2': 'no label', 'O_Particolari_3': 'no label', 'P_Uso_edif_1': 'no label', 'P_Uso_edif_2': 'no label', 'Q_Ristrutt': 'no label', 'T_Note_dem': 'no label', 'U_Reti_tecn_1': 'no label', 'U_Reti_tecn_2': 'no label', 'V_Uso_area_1': 'no label', 'V_Uso_area_2': 'no label', 'V_Uso_area_3': 'no label', 'stato': 'no label', 'GRADO D\'INTERVENTO': 'no label', 'PRESCRIZIONI': 'no label', 'VINCOLO AMBIENTALE': 'no label', 'scheda_agg': 'no label', 'Cat.2026': 'no label', 'pdf_web': 'no label', 'html_link': 'no label', });
lyr_Elementiartisticidipregiocornicimodanateaffreschifregi_4.set('fieldLabels', {'fid': 'no label', 'scheda': 'no label', 'Stato_2025': 'no label', 'pdf_link': 'no label', 'A_Solaio_1': 'no label', 'A_Solaio_2': 'no label', 'B_Copert_tipo_1': 'no label', 'B_Copert_tipo_2': 'no label', 'B_Copert_tipo_3': 'no label', 'B_Copert_tipo_4': 'no label', 'C_Copert_str_1': 'no label', 'C_Copert_str_2': 'no label', 'C_Copert_str_3': 'no label', 'D_Gronda_1': 'no label', 'D_Gronda_2': 'no label', 'E_Pluv_can_1': 'no label', 'E_Pluv_can_2': 'no label', 'F_Muri_1': 'no label', 'F_Muri_2': 'no label', 'F_Muri_3': 'no label', 'G_Finestre_1': 'no label', 'G_Finestre_2': 'no label', 'H_Oscuranti_1': 'no label', 'H_Oscuranti_2': 'no label', 'H_Oscuranti_3': 'no label', 'I_Porte_1': 'no label', 'I_Porte_2': 'no label', 'I_Porte_3': 'no label', 'J_Cornici_fin_1': 'no label', 'J_Cornici_fin_2': 'no label', 'J_Cornici_fin_3': 'no label', 'J_Cornici_fin_4': 'no label', 'J_Cornici_fin_5': 'no label', 'K_Cornici_por_1': 'no label', 'K_Cornici_por_2': 'no label', 'K_Cornici_por_3': 'no label', 'K_Cornici_por_4': 'no label', 'L_Balc_strutt_1': 'no label', 'L_Balc_strutt_2': 'no label', 'M_Balc_par_1': 'no label', 'M_Balc_par_2': 'no label', 'N_Valore_1': 'no label', 'N_Valore_2': 'no label', 'O_Particolari_1': 'no label', 'O_Particolari_2': 'no label', 'O_Particolari_3': 'no label', 'P_Uso_edif_1': 'no label', 'P_Uso_edif_2': 'no label', 'Q_Ristrutt': 'no label', 'T_Note_dem': 'no label', 'U_Reti_tecn_1': 'no label', 'U_Reti_tecn_2': 'no label', 'V_Uso_area_1': 'no label', 'V_Uso_area_2': 'no label', 'V_Uso_area_3': 'no label', 'stato': 'no label', 'GRADO D\'INTERVENTO': 'no label', 'PRESCRIZIONI': 'no label', 'VINCOLO AMBIENTALE': 'no label', 'scheda_agg': 'no label', 'Cat.2026': 'no label', 'pdf_web': 'no label', 'html_link': 'no label', });
lyr_Aperturetrilitiche_5.set('fieldLabels', {'fid': 'no label', 'scheda': 'no label', 'Stato_2025': 'no label', 'pdf_link': 'no label', 'A_Solaio_1': 'no label', 'A_Solaio_2': 'no label', 'B_Copert_tipo_1': 'no label', 'B_Copert_tipo_2': 'no label', 'B_Copert_tipo_3': 'no label', 'B_Copert_tipo_4': 'no label', 'C_Copert_str_1': 'no label', 'C_Copert_str_2': 'no label', 'C_Copert_str_3': 'no label', 'D_Gronda_1': 'no label', 'D_Gronda_2': 'no label', 'E_Pluv_can_1': 'no label', 'E_Pluv_can_2': 'no label', 'F_Muri_1': 'no label', 'F_Muri_2': 'no label', 'F_Muri_3': 'no label', 'G_Finestre_1': 'no label', 'G_Finestre_2': 'no label', 'H_Oscuranti_1': 'no label', 'H_Oscuranti_2': 'no label', 'H_Oscuranti_3': 'no label', 'I_Porte_1': 'no label', 'I_Porte_2': 'no label', 'I_Porte_3': 'no label', 'J_Cornici_fin_1': 'no label', 'J_Cornici_fin_2': 'no label', 'J_Cornici_fin_3': 'no label', 'J_Cornici_fin_4': 'no label', 'J_Cornici_fin_5': 'no label', 'K_Cornici_por_1': 'no label', 'K_Cornici_por_2': 'no label', 'K_Cornici_por_3': 'no label', 'K_Cornici_por_4': 'no label', 'L_Balc_strutt_1': 'no label', 'L_Balc_strutt_2': 'no label', 'M_Balc_par_1': 'no label', 'M_Balc_par_2': 'no label', 'N_Valore_1': 'no label', 'N_Valore_2': 'no label', 'O_Particolari_1': 'no label', 'O_Particolari_2': 'no label', 'O_Particolari_3': 'no label', 'P_Uso_edif_1': 'no label', 'P_Uso_edif_2': 'no label', 'Q_Ristrutt': 'no label', 'T_Note_dem': 'no label', 'U_Reti_tecn_1': 'no label', 'U_Reti_tecn_2': 'no label', 'V_Uso_area_1': 'no label', 'V_Uso_area_2': 'no label', 'V_Uso_area_3': 'no label', 'stato': 'no label', 'GRADO D\'INTERVENTO': 'no label', 'PRESCRIZIONI': 'no label', 'VINCOLO AMBIENTALE': 'no label', 'scheda_agg': 'no label', 'Cat.2026': 'no label', 'pdf_web': 'no label', 'html_link': 'no label', });
lyr_AperturetradizionaliaTconserramentoinlegno_6.set('fieldLabels', {'fid': 'no label', 'scheda': 'no label', 'Stato_2025': 'no label', 'pdf_link': 'no label', 'A_Solaio_1': 'no label', 'A_Solaio_2': 'no label', 'B_Copert_tipo_1': 'no label', 'B_Copert_tipo_2': 'no label', 'B_Copert_tipo_3': 'no label', 'B_Copert_tipo_4': 'no label', 'C_Copert_str_1': 'no label', 'C_Copert_str_2': 'no label', 'C_Copert_str_3': 'no label', 'D_Gronda_1': 'no label', 'D_Gronda_2': 'no label', 'E_Pluv_can_1': 'no label', 'E_Pluv_can_2': 'no label', 'F_Muri_1': 'no label', 'F_Muri_2': 'no label', 'F_Muri_3': 'no label', 'G_Finestre_1': 'no label', 'G_Finestre_2': 'no label', 'H_Oscuranti_1': 'no label', 'H_Oscuranti_2': 'no label', 'H_Oscuranti_3': 'no label', 'I_Porte_1': 'no label', 'I_Porte_2': 'no label', 'I_Porte_3': 'no label', 'J_Cornici_fin_1': 'no label', 'J_Cornici_fin_2': 'no label', 'J_Cornici_fin_3': 'no label', 'J_Cornici_fin_4': 'no label', 'J_Cornici_fin_5': 'no label', 'K_Cornici_por_1': 'no label', 'K_Cornici_por_2': 'no label', 'K_Cornici_por_3': 'no label', 'K_Cornici_por_4': 'no label', 'L_Balc_strutt_1': 'no label', 'L_Balc_strutt_2': 'no label', 'M_Balc_par_1': 'no label', 'M_Balc_par_2': 'no label', 'N_Valore_1': 'no label', 'N_Valore_2': 'no label', 'O_Particolari_1': 'no label', 'O_Particolari_2': 'no label', 'O_Particolari_3': 'no label', 'P_Uso_edif_1': 'no label', 'P_Uso_edif_2': 'no label', 'Q_Ristrutt': 'no label', 'T_Note_dem': 'no label', 'U_Reti_tecn_1': 'no label', 'U_Reti_tecn_2': 'no label', 'V_Uso_area_1': 'no label', 'V_Uso_area_2': 'no label', 'V_Uso_area_3': 'no label', 'stato': 'no label', 'GRADO D\'INTERVENTO': 'no label', 'PRESCRIZIONI': 'no label', 'VINCOLO AMBIENTALE': 'no label', 'scheda_agg': 'no label', 'Cat.2026': 'no label', 'pdf_web': 'no label', 'html_link': 'no label', });
lyr_Tettoincoppidilaterizio_7.set('fieldLabels', {'fid': 'no label', 'scheda': 'no label', 'Stato_2025': 'no label', 'pdf_link': 'no label', 'A_Solaio_1': 'no label', 'A_Solaio_2': 'no label', 'B_Copert_tipo_1': 'no label', 'B_Copert_tipo_2': 'no label', 'B_Copert_tipo_3': 'no label', 'B_Copert_tipo_4': 'no label', 'C_Copert_str_1': 'no label', 'C_Copert_str_2': 'no label', 'C_Copert_str_3': 'no label', 'D_Gronda_1': 'no label', 'D_Gronda_2': 'no label', 'E_Pluv_can_1': 'no label', 'E_Pluv_can_2': 'no label', 'F_Muri_1': 'no label', 'F_Muri_2': 'no label', 'F_Muri_3': 'no label', 'G_Finestre_1': 'no label', 'G_Finestre_2': 'no label', 'H_Oscuranti_1': 'no label', 'H_Oscuranti_2': 'no label', 'H_Oscuranti_3': 'no label', 'I_Porte_1': 'no label', 'I_Porte_2': 'no label', 'I_Porte_3': 'no label', 'J_Cornici_fin_1': 'no label', 'J_Cornici_fin_2': 'no label', 'J_Cornici_fin_3': 'no label', 'J_Cornici_fin_4': 'no label', 'J_Cornici_fin_5': 'no label', 'K_Cornici_por_1': 'no label', 'K_Cornici_por_2': 'no label', 'K_Cornici_por_3': 'no label', 'K_Cornici_por_4': 'no label', 'L_Balc_strutt_1': 'no label', 'L_Balc_strutt_2': 'no label', 'M_Balc_par_1': 'no label', 'M_Balc_par_2': 'no label', 'N_Valore_1': 'no label', 'N_Valore_2': 'no label', 'O_Particolari_1': 'no label', 'O_Particolari_2': 'no label', 'O_Particolari_3': 'no label', 'P_Uso_edif_1': 'no label', 'P_Uso_edif_2': 'no label', 'Q_Ristrutt': 'no label', 'T_Note_dem': 'no label', 'U_Reti_tecn_1': 'no label', 'U_Reti_tecn_2': 'no label', 'V_Uso_area_1': 'no label', 'V_Uso_area_2': 'no label', 'V_Uso_area_3': 'no label', 'stato': 'no label', 'GRADO D\'INTERVENTO': 'no label', 'PRESCRIZIONI': 'no label', 'VINCOLO AMBIENTALE': 'no label', 'scheda_agg': 'no label', 'Cat.2026': 'no label', 'pdf_web': 'no label', 'html_link': 'no label', });
lyr_Tettiinardesia_8.set('fieldLabels', {'fid': 'no label', 'scheda': 'no label', 'Stato_2025': 'no label', 'pdf_link': 'no label', 'A_Solaio_1': 'no label', 'A_Solaio_2': 'no label', 'B_Copert_tipo_1': 'no label', 'B_Copert_tipo_2': 'no label', 'B_Copert_tipo_3': 'no label', 'B_Copert_tipo_4': 'no label', 'C_Copert_str_1': 'no label', 'C_Copert_str_2': 'no label', 'C_Copert_str_3': 'no label', 'D_Gronda_1': 'no label', 'D_Gronda_2': 'no label', 'E_Pluv_can_1': 'no label', 'E_Pluv_can_2': 'no label', 'F_Muri_1': 'no label', 'F_Muri_2': 'no label', 'F_Muri_3': 'no label', 'G_Finestre_1': 'no label', 'G_Finestre_2': 'no label', 'H_Oscuranti_1': 'no label', 'H_Oscuranti_2': 'no label', 'H_Oscuranti_3': 'no label', 'I_Porte_1': 'no label', 'I_Porte_2': 'no label', 'I_Porte_3': 'no label', 'J_Cornici_fin_1': 'no label', 'J_Cornici_fin_2': 'no label', 'J_Cornici_fin_3': 'no label', 'J_Cornici_fin_4': 'no label', 'J_Cornici_fin_5': 'no label', 'K_Cornici_por_1': 'no label', 'K_Cornici_por_2': 'no label', 'K_Cornici_por_3': 'no label', 'K_Cornici_por_4': 'no label', 'L_Balc_strutt_1': 'no label', 'L_Balc_strutt_2': 'no label', 'M_Balc_par_1': 'no label', 'M_Balc_par_2': 'no label', 'N_Valore_1': 'no label', 'N_Valore_2': 'no label', 'O_Particolari_1': 'no label', 'O_Particolari_2': 'no label', 'O_Particolari_3': 'no label', 'P_Uso_edif_1': 'no label', 'P_Uso_edif_2': 'no label', 'Q_Ristrutt': 'no label', 'T_Note_dem': 'no label', 'U_Reti_tecn_1': 'no label', 'U_Reti_tecn_2': 'no label', 'V_Uso_area_1': 'no label', 'V_Uso_area_2': 'no label', 'V_Uso_area_3': 'no label', 'stato': 'no label', 'GRADO D\'INTERVENTO': 'no label', 'PRESCRIZIONI': 'no label', 'VINCOLO AMBIENTALE': 'no label', 'scheda_agg': 'no label', 'Cat.2026': 'no label', 'pdf_web': 'no label', 'html_link': 'no label', });
lyr_Tettiinpiode_9.set('fieldLabels', {'fid': 'no label', 'scheda': 'no label', 'Stato_2025': 'no label', 'pdf_link': 'no label', 'A_Solaio_1': 'no label', 'A_Solaio_2': 'no label', 'B_Copert_tipo_1': 'no label', 'B_Copert_tipo_2': 'hidden field', 'B_Copert_tipo_3': 'hidden field', 'B_Copert_tipo_4': 'hidden field', 'C_Copert_str_1': 'no label', 'C_Copert_str_2': 'no label', 'C_Copert_str_3': 'no label', 'D_Gronda_1': 'no label', 'D_Gronda_2': 'no label', 'E_Pluv_can_1': 'no label', 'E_Pluv_can_2': 'no label', 'F_Muri_1': 'no label', 'F_Muri_2': 'no label', 'F_Muri_3': 'no label', 'G_Finestre_1': 'no label', 'G_Finestre_2': 'no label', 'H_Oscuranti_1': 'no label', 'H_Oscuranti_2': 'no label', 'H_Oscuranti_3': 'no label', 'I_Porte_1': 'no label', 'I_Porte_2': 'no label', 'I_Porte_3': 'no label', 'J_Cornici_fin_1': 'no label', 'J_Cornici_fin_2': 'no label', 'J_Cornici_fin_3': 'no label', 'J_Cornici_fin_4': 'no label', 'J_Cornici_fin_5': 'no label', 'K_Cornici_por_1': 'no label', 'K_Cornici_por_2': 'no label', 'K_Cornici_por_3': 'no label', 'K_Cornici_por_4': 'no label', 'L_Balc_strutt_1': 'no label', 'L_Balc_strutt_2': 'no label', 'M_Balc_par_1': 'no label', 'M_Balc_par_2': 'no label', 'N_Valore_1': 'no label', 'N_Valore_2': 'no label', 'O_Particolari_1': 'no label', 'O_Particolari_2': 'no label', 'O_Particolari_3': 'no label', 'P_Uso_edif_1': 'no label', 'P_Uso_edif_2': 'no label', 'Q_Ristrutt': 'no label', 'T_Note_dem': 'no label', 'U_Reti_tecn_1': 'no label', 'U_Reti_tecn_2': 'no label', 'V_Uso_area_1': 'no label', 'V_Uso_area_2': 'no label', 'V_Uso_area_3': 'no label', 'stato': 'no label', 'GRADO D\'INTERVENTO': 'no label', 'PRESCRIZIONI': 'no label', 'VINCOLO AMBIENTALE': 'no label', 'scheda_agg': 'no label', 'Cat.2026': 'no label', 'pdf_web': 'no label', 'html_link': 'no label', });
lyr_Edificischedati_10.set('fieldLabels', {'fid': 'hidden field', 'scheda': 'header label - always visible', 'Stato_2025': 'hidden field', 'pdf_link': 'hidden field', 'A_Solaio_1': 'hidden field', 'A_Solaio_2': 'hidden field', 'B_Copert_tipo_1': 'hidden field', 'B_Copert_tipo_2': 'hidden field', 'B_Copert_tipo_3': 'hidden field', 'B_Copert_tipo_4': 'hidden field', 'C_Copert_str_1': 'hidden field', 'C_Copert_str_2': 'hidden field', 'C_Copert_str_3': 'hidden field', 'D_Gronda_1': 'hidden field', 'D_Gronda_2': 'hidden field', 'E_Pluv_can_1': 'hidden field', 'E_Pluv_can_2': 'hidden field', 'F_Muri_1': 'hidden field', 'F_Muri_2': 'hidden field', 'F_Muri_3': 'hidden field', 'G_Finestre_1': 'hidden field', 'G_Finestre_2': 'hidden field', 'H_Oscuranti_1': 'hidden field', 'H_Oscuranti_2': 'hidden field', 'H_Oscuranti_3': 'hidden field', 'I_Porte_1': 'hidden field', 'I_Porte_2': 'hidden field', 'I_Porte_3': 'hidden field', 'J_Cornici_fin_1': 'hidden field', 'J_Cornici_fin_2': 'hidden field', 'J_Cornici_fin_3': 'hidden field', 'J_Cornici_fin_4': 'hidden field', 'J_Cornici_fin_5': 'hidden field', 'K_Cornici_por_1': 'hidden field', 'K_Cornici_por_2': 'hidden field', 'K_Cornici_por_3': 'hidden field', 'K_Cornici_por_4': 'hidden field', 'L_Balc_strutt_1': 'hidden field', 'L_Balc_strutt_2': 'hidden field', 'M_Balc_par_1': 'hidden field', 'M_Balc_par_2': 'hidden field', 'N_Valore_1': 'hidden field', 'N_Valore_2': 'hidden field', 'O_Particolari_1': 'hidden field', 'O_Particolari_2': 'hidden field', 'O_Particolari_3': 'hidden field', 'P_Uso_edif_1': 'hidden field', 'P_Uso_edif_2': 'hidden field', 'Q_Ristrutt': 'hidden field', 'T_Note_dem': 'hidden field', 'U_Reti_tecn_1': 'hidden field', 'U_Reti_tecn_2': 'hidden field', 'V_Uso_area_1': 'hidden field', 'V_Uso_area_2': 'hidden field', 'V_Uso_area_3': 'hidden field', 'stato': 'hidden field', 'GRADO D\'INTERVENTO': 'hidden field', 'PRESCRIZIONI': 'hidden field', 'VINCOLO AMBIENTALE': 'hidden field', 'scheda_agg': 'hidden field', 'Cat.2026': 'inline label - always visible', 'pdf_web': 'hidden field', 'html_link': 'inline label - visible with data', });
lyr_Confinecomunale_11.set('fieldLabels', {'fid': 'no label', 'OBJECTID': 'no label', 'CLASSREF': 'no label', 'BELFIORE': 'no label', 'COD_ISTATN': 'no label', 'NOME_COM': 'no label', 'COD_PRO': 'no label', 'NOME_PRO': 'no label', 'SIG_PRO': 'no label', 'COD_CMO': 'no label', 'NOME_CMO': 'no label', 'COD_ASL': 'no label', 'NOME_ASL': 'no label', 'COD_REG': 'no label', 'NOME_REG': 'no label', 'ANNO': 'no label', 'ISTAT': 'no label', 'LEGGE_ISTI': 'no label', 'ATS_COD': 'no label', 'ATS_DEC': 'no label', 'CMETR_COD': 'no label', 'CMETR_DEC': 'no label', 'SHAPE_AREA': 'no label', 'SHAPE_LEN': 'no label', });
lyr_Confinecomunale_11.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});